# Configuration for GitHub's automatic release notes generator
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
  categories:
    - title: "New Features"
      labels:
        - feat
        - feature
        - enhancement
    - title: "Bug Fixes"
      labels:
        - fix
        - bugfix
        - bug
    - title: "Performance"
      labels:
        - perf
        - performance
    - title: "Documentation"
      labels:
        - docs
        - documentation
    - title: "Other Changes"
      labels:
        - "*"
